name: Cartograph
version: '${version}'
main: gg.cartograph.plugin.paper.CartographPaperPlugin
api-version: '26.1'
description: Cartograph metrics plugin
dependencies:
  server:
    ViaVersion:
      load: BEFORE
      required: false
      join-classpath: true
    Geyser-Spigot:
      load: BEFORE
      required: false
      join-classpath: true
    floodgate:
      load: BEFORE
      required: false
      join-classpath: true
