modLoader = "javafml"
loaderVersion = "[1,)"
license = "All Rights Reserved"

[[mods]]
modId = "cartograph"
version = "1.0.0-SNAPSHOT"
displayName = "Cartograph"
description = "Cartograph metrics plugin"
authors = "Cartograph"

[[dependencies.cartograph]]
modId = "neoforge"
type = "required"
versionRange = "[26.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cartograph]]
modId = "minecraft"
type = "required"
versionRange = "[26.1,26.2)"
ordering = "NONE"
side = "BOTH"
