modLoader = "javafml"
loaderVersion = "[1,)"
license = "All Rights Reserved"

[[mixins]]
config = "cartograph.mixins.json"

[[mods]]
modId = "cartograph"
version = "${version}"
displayName = "Cartograph"
description = "Cartograph metrics plugin"
authors = "Cartograph"

[[dependencies.cartograph]]
modId = "neoforge"
type = "required"
versionRange = "[26.1.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cartograph]]
modId = "minecraft"
type = "required"
versionRange = "[26.1,26.2)"
ordering = "NONE"
side = "BOTH"
